name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dev
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.11.1
          - 4.10.1
          - 4.09.1
          - 4.08.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Retrieve opam cache
        uses: actions/cache@v2
        if: runner.os != 'Windows'
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-${{ hashFiles('*.opam.locked') }}
          restore-keys: |
            v2-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libpq-dev
          opam pin add -y .
          opam depext -y demo
      - name: Install dependencies
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          opam install -y . --deps-only --with-doc --with-test --locked --unlock-base
          opam install -y caqti-driver-postgresql alcotest-lwt
      - name: Recover from an Opam broken state
        if: steps.cache-opam.outputs.cache-hit == 'true'
        run: opam upgrade --fixup
      - name: Build
        run: make build
      - name: Run unit tests
        run: make test
      - name: Run slow tests
        run: make test-slow
